// Fill out your copyright notice in the Description page of Project Settings.

#include "FPSProject.h"
#include "FPSGameMode.h"

//#include "FPSCharacter.h" <--- no longer in use as the blueprint class is
// being referenced

AFPSGameMode::AFPSGameMode(const class FObjectInitializer &ObjectInitializer)
    : Super(ObjectInitializer) {

  //  DefaultPawnClass = AFPSCharacter::StaticClass();

  // Set default pawn class to the inherited blueprint class
  static ConstructorHelpers::FClassFinder<APawn> PlayerPawnObject(
      TEXT("Pawn'/Game/Blueprints/BP_FPSCharacter.BP_FPSCharacter_C'"));
  // "This code will find the class generated by your blueprint and assign it as
  // your default pawn class."
      
  if (PlayerPawnObject.Class != NULL) {
    DefaultPawnClass = PlayerPawnObject.Class;
  }
}

void AFPSGameMode::StartPlay() {
  Super::StartPlay();

  StartMatch();

  //  if (GEngine) {
  //    GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Yellow,
  //                                     TEXT("Hello World"));
  //  }
  
}
